<a href="https://colab.research.google.com/github/juurie/Projects/blob/main/2023_smartfarm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install category_encoders

Collecting category_encoders
  Downloading category_encoders-2.6.2-py2.py3-none-any.whl (81 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.8/81.8 kB 1.5 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.23.5)
Requirement already satisfied: scikit-learn>=0.20.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.2.2)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.11.2)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (0.14.0)
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.5.3)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (0.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.5->category_encoders) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.5->category_encoders) (2023.3.post1)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from patsy>=0.5.1->category_encoders) (1.16.0)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20.0->category_encoders) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20.0->category_encoders) (3.2.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.10/dist-packages (from statsmodels>=0.9.0->category_encoders) (23.1)
Installing collected packages: category_encoders
Successfully installed category_encoders-2.6.2

In [ ]:
import requests
import re
import matplotlib.pyplot as plt
from collections import Counter
from PIL import Image
import seaborn as sns
import os
import pandas as pd
from sklearn.preprocessing import LabelEncoder
# import lightgbm as lgb
import gc
import plotly.graph_objects as go
from ipywidgets import interact, interact_manual
import ipywidgets as widgets
import plotly.express as px
#

from pandas import DataFrame
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
from sklearn.feature_selection import f_regression,chi2, SelectKBest
from sklearn.model_selection import cross_val_score # 이값이 높은걸 선택하면 됨
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_predict
from sklearn import model_selection
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestRegressor
from lightgbm import LGBMRegressor
from sklearn.svm import SVC
from xgboost import XGBRegressor
# from ngboost import NGBRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import ExtraTreesRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import BaggingRegressor
from sklearn.ensemble import VotingRegressor
# from catboost import CatBoostRegressor
from tqdm import tqdm
from category_encoders import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import KFold
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import Normalizer
import category_encoders as ce
#from sklearn.feature_selection import chi2, SelectKBest

# 결과 확인을 용이하게 하기 위한 코드
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
%matplotlib inline
%pylab inline

Populating the interactive namespace from numpy and matplotlib

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [5]:
!git clone https://(juurie):(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)@github.com/(juurie)/(project).git

/bin/bash: -c: line 1: syntax error near unexpected token `('
/bin/bash: -c: line 1: `git clone https://(juurie):(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)@github.com/(juurie)/(project).git'

In [7]:
cd Commit_Folder

[Errno 2] No such file or directory: 'Commit_Folder'
/content

# 새 섹션

In [ ]:
# csv to parquet -> 메모리에 효율적인 데이터 유형을 사용하여 용량을 크게 줄이고 빠른 작업이 가능합니다.
def csv_to_parquet(csv_path, save_name):
    df = pd.read_csv(csv_path)
    df.to_parquet(f'./{save_name}.parquet')
    del df
    gc.collect()
    print(save_name, 'Done.')

In [ ]:
csv_to_parquet('/content/drive/MyDrive/2023 스마트농업/SAMPLE/SAMPLE/2023_smartFarm_AI_hackathon_dataset.csv', 'input_data')

input_data Done.

In [ ]:
#  -------------------------------------------
"""
입출력 양식을
준수해 주십시오

###  INPUT ###
import pandas as pd
input_data = pd.read_csv('2023_smartFarm_AI_hackathon_dataset.csv')

{

        Write codes...

    Training model name : model
    ex) y_pred = model.predict(X_test)


}


### OUTPUT ###
print("RMSE:", rmse)
print("R2_score:", r2score)
"""

'\n입출력 양식을 \n준수해 주십시오\n\n###  INPUT ###\nimport pandas as pd\ninput_data = pd.read_csv(\'2023_smartFarm_AI_hackathon_dataset.csv\')\n\n{\n    \n        Write codes...\n    \n    Training model name : model\n    ex) y_pred = model.predict(X_test)\n    \n\n}\n\n\n### OUTPUT ###\nprint("RMSE:", rmse)\nprint("R2_score:", r2score)\n'

In [ ]:


# ------------------------------------------------


#      SAMPLE MODEL


# ------------------------------------------------


###  INPUT ###
"""

Read CSV files from the given list of file paths and return DataFrames.

"""

import pandas as pd

# input_data = pd.read_csv("2023_smartFarm_AI_hackathon_dataset.csv")
# 데이터 불러오기
input_data = pd.read_parquet('./input_data.parquet')
#  -------------------------------------------
###    Write codes...  ###
#      EXAMPLE CODE      #




# Read CSV files from the lists of file paths


# Now you have lists of DataFrames for each type of data

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

# ... (Data preprocessing code here)

'\n\nRead CSV files from the given list of file paths and return DataFrames.\n\n'

In [ ]:
input_data = input_data.drop(columns=['frmDist'])

input_data

,date,inTp,inHd,otmsuplyqy,acSlrdQy,cunt,ph,outTp,outWs,daysuplyqy,...,outtrn_cumsum,WaterUsage,WaterCost,FertilizerUsage,FertilizerCost,CO2Usage,CO2Cost,MistUsageTime,Mist Cost,HeatingEnergyUsage_cumsum
0,20220926,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.0
1,20221001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,1347.554178,202.133127,4711.308821,5936.249114,0.000000,0.0000,190.168990,2221.173803,0.0
2,20221002,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,69.899353,10.484903,271.379890,341.938662,0.000000,0.0000,0.000000,0.000000,0.0
3,20221003,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,412.225065,61.833760,1539.505534,1939.776973,253.744916,149.7095,0.000000,0.000000,0.0
4,20221004,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,590.608634,88.591295,2614.973165,3294.866187,3032.885084,1789.4022,1.149739,13.428955,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84835,20180710,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,235272.042536,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.0
84836,20180711,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,227947.124946,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.0
84837,20180712,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,231527.426327,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.0
84838,20180713,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,251254.321635,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.0
84839,20180714,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.0

In [ ]:
input_data["date"] = pd.to_datetime(input_data["date"],format='%Y%m%d')
# input_data['year']= input_data['date'].dt.year
input_data['month']= input_data['date'].dt.month
# input_data['day']= input_data['date'].dt.day
input_data

,date,inTp,inHd,otmsuplyqy,acSlrdQy,cunt,ph,outTp,outWs,daysuplyqy,...,WaterUsage,WaterCost,FertilizerUsage,FertilizerCost,CO2Usage,CO2Cost,MistUsageTime,Mist Cost,HeatingEnergyUsage_cumsum,month
0,2022-09-26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.0,9
1,2022-10-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1347.554178,202.133127,4711.308821,5936.249114,0.000000,0.0000,190.168990,2221.173803,0.0,10
2,2022-10-02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,69.899353,10.484903,271.379890,341.938662,0.000000,0.0000,0.000000,0.000000,0.0,10
3,2022-10-03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,412.225065,61.833760,1539.505534,1939.776973,253.744916,149.7095,0.000000,0.000000,0.0,10
4,2022-10-04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,590.608634,88.591295,2614.973165,3294.866187,3032.885084,1789.4022,1.149739,13.428955,0.0,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84835,2018-07-10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.0,7
84836,2018-07-11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.0,7
84837,2018-07-12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.0,7
84838,2018-07-13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.0,7
84839,2018-07-14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.0,7

In [ ]:
#계절 변수를 미리 생성
input_data['season']='season'

input_data.loc[(input_data['month']>=2) & (input_data['month']<5) ,['season']]= 'spring'
input_data.loc[(input_data['month']>=5) & (input_data['month']<8) ,['season']]= 'summer'
input_data.loc[(input_data['month']>=8) & (input_data['month']<11),['season']]= 'autumn'
input_data.loc[(input_data['month']>=11) & (input_data['month']<13) & (input_data['month']==1),['season']]= 'winter'

In [ ]:
input_data

,date,inTp,inHd,otmsuplyqy,acSlrdQy,cunt,ph,outTp,outWs,daysuplyqy,...,WaterCost,FertilizerUsage,FertilizerCost,CO2Usage,CO2Cost,MistUsageTime,Mist Cost,HeatingEnergyUsage_cumsum,month,season
0,2022-09-26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.0,9,autumn
1,2022-10-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,202.133127,4711.308821,5936.249114,0.000000,0.0000,190.168990,2221.173803,0.0,10,autumn
2,2022-10-02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.484903,271.379890,341.938662,0.000000,0.0000,0.000000,0.000000,0.0,10,autumn
3,2022-10-03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,61.833760,1539.505534,1939.776973,253.744916,149.7095,0.000000,0.000000,0.0,10,autumn
4,2022-10-04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,88.591295,2614.973165,3294.866187,3032.885084,1789.4022,1.149739,13.428955,0.0,10,autumn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84835,2018-07-10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.0,7,summer
84836,2018-07-11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.0,7,summer
84837,2018-07-12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.0,7,summer
84838,2018-07-13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.0,7,summer
84839,2018-07-14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.0,7,summer

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from category_encoders import OneHotEncoder
encoder = OneHotEncoder(use_cat_names = True)
df_onehot = encoder.fit_transform(input_data[['season']])

In [ ]:
df_onehot

       season_autumn  season_season  season_spring  season_summer
0                  1              0              0              0
1                  1              0              0              0
2                  1              0              0              0
3                  1              0              0              0
4                  1              0              0              0
...              ...            ...            ...            ...
84835              0              0              0              1
84836              0              0              0              1
84837              0              0              0              1
84838              0              0              0              1
84839              0              0              0              1

[84840 rows x 4 columns]

In [ ]:
input_ohe = pd.concat([input_data, df_onehot],axis=1)
# input_ohe = input_data.drop(columns=['season'])

In [ ]:
input_ohe = input_ohe.drop(columns=['season'])
input_ohe

,date,inTp,inHd,otmsuplyqy,acSlrdQy,cunt,ph,outTp,outWs,daysuplyqy,...,CO2Usage,CO2Cost,MistUsageTime,Mist Cost,HeatingEnergyUsage_cumsum,month,season_autumn,season_season,season_spring,season_summer
0,2022-09-26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0000,0.000000,0.000000,0.0,9,1,0,0,0
1,2022-10-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0000,190.168990,2221.173803,0.0,10,1,0,0,0
2,2022-10-02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0000,0.000000,0.000000,0.0,10,1,0,0,0
3,2022-10-03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,253.744916,149.7095,0.000000,0.000000,0.0,10,1,0,0,0
4,2022-10-04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3032.885084,1789.4022,1.149739,13.428955,0.0,10,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84835,2018-07-10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0000,0.000000,0.000000,0.0,7,0,0,0,1
84836,2018-07-11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0000,0.000000,0.000000,0.0,7,0,0,0,1
84837,2018-07-12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0000,0.000000,0.000000,0.0,7,0,0,0,1
84838,2018-07-13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0000,0.000000,0.000000,0.0,7,0,0,0,1
84839,2018-07-14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0000,0.000000,0.000000,0.0,7,0,0,0,1

In [ ]:
# Split the data into training and testing sets
X = input_ohe[input_ohe.drop(columns=['date','outtrn_cumsum','HeatingEnergyUsage_cumsum']).columns]
Y = input_ohe[['outtrn_cumsum','HeatingEnergyUsage_cumsum']]

In [ ]:
input_ohe

,date,inTp,inHd,otmsuplyqy,acSlrdQy,cunt,ph,outTp,outWs,daysuplyqy,...,CO2Usage,CO2Cost,MistUsageTime,Mist Cost,HeatingEnergyUsage_cumsum,month,season_autumn,season_season,season_spring,season_summer
0,2022-09-26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0000,0.000000,0.000000,0.0,9,1,0,0,0
1,2022-10-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0000,190.168990,2221.173803,0.0,10,1,0,0,0
2,2022-10-02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0000,0.000000,0.000000,0.0,10,1,0,0,0
3,2022-10-03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,253.744916,149.7095,0.000000,0.000000,0.0,10,1,0,0,0
4,2022-10-04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3032.885084,1789.4022,1.149739,13.428955,0.0,10,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84835,2018-07-10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0000,0.000000,0.000000,0.0,7,0,0,0,1
84836,2018-07-11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0000,0.000000,0.000000,0.0,7,0,0,0,1
84837,2018-07-12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0000,0.000000,0.000000,0.0,7,0,0,0,1
84838,2018-07-13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0000,0.000000,0.000000,0.0,7,0,0,0,1
84839,2018-07-14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0000,0.000000,0.000000,0.0,7,0,0,0,1

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,Y,random_state=121)

In [ ]:
X_train

,inTp,inHd,otmsuplyqy,acSlrdQy,cunt,ph,outTp,outWs,daysuplyqy,inCo2,...,FertilizerCost,CO2Usage,CO2Cost,MistUsageTime,Mist Cost,month,season_autumn,season_season,season_spring,season_summer
36991,23.431263,103.492030,0.000000,322.643227,0.000000,0.000000,19.728525,0.000000,0.0,503.768915,...,0.000000,0.0,0.0,0.000000,0.000000,9,1,0,0,0
20621,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.000000,0.0,0.0,0.000000,0.000000,7,0,0,0,1
71537,12.925242,101.026797,100.178869,0.000000,1.796743,5.728743,1.824471,0.000000,0.0,493.001143,...,0.000000,0.0,0.0,0.000000,0.000000,1,0,1,0,0
18305,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,4815.718169,0.0,0.0,44.442846,519.092441,10,1,0,0,0
28398,18.305197,88.792292,110.576604,892.073702,5.366466,5.145688,5.968696,0.905147,0.0,568.647331,...,0.000000,0.0,0.0,0.000000,0.000000,2,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30754,19.501571,92.356056,62.105971,0.000000,4.525523,5.968313,7.484151,1.202599,0.0,607.259809,...,0.000000,0.0,0.0,0.000000,0.000000,11,0,1,0,0
36351,18.273175,74.465887,59.021730,1143.128054,6.820073,4.746958,-1.027700,2.086335,0.0,667.754367,...,0.000000,0.0,0.0,0.000000,0.000000,12,0,1,0,0
51265,23.782012,82.842609,48.592424,1136.160490,9.402627,6.363840,27.187771,1.142951,0.0,384.542056,...,0.000000,0.0,0.0,0.000000,0.000000,9,1,0,0,0
56584,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.000000,0.0,0.0,0.000000,0.000000,6,0,0,0,1
11586,27.540759,91.941028,0.000000,1672.529907,0.000000,0.000000,22.734022,0.000000,0.0,368.872939,...,0.000000,0.0,0.0,0.000000,0.000000,7,0,0,0,1

In [ ]:
y_train

       outtrn_cumsum  HeatingEnergyUsage_cumsum
36991    1178.897289               0.000000e+00
20621   90428.866166               0.000000e+00
71537   21044.297475               0.000000e+00
18305       0.000000               2.618298e+06
28398   45898.347781               0.000000e+00
...              ...                        ...
30754   19068.467115               0.000000e+00
36351    6591.935740               0.000000e+00
51265       0.000000               0.000000e+00
56584       0.000000               0.000000e+00
11586       0.000000               0.000000e+00

[63630 rows x 2 columns]

In [ ]:
# Calculate RMSE between the predictions and actual 'y' values
def calculate_rmse(targets, predictions):
    """
    Calculate the Root Mean Squared Error (RMSE) between predicted and target values.

    :param predictions: Predicted values.
    :type predictions: array-like
    :param targets: Target values.
    :type targets: array-like
    :return: RMSE value.
    :rtype: float
    """
    from sklearn.metrics import mean_squared_error
    return np.sqrt(mean_squared_error(targets, predictions))


# Calculate r2_score between the predictions and actual 'y' values
def calculate_R2_score(y_test,y_pred):
    from sklearn.metrics import r2_score
    return r2_score(y_test, y_pred)

In [ ]:
# multioutput

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.ensemble import ExtraTreesRegressor  # Import ExtraTreesRegressor
from sklearn.multioutput import MultiOutputRegressor


# Create an ExtraTreesRegressor with MultiOutputRegressor for multi-output regression
model = MultiOutputRegressor(ExtraTreesRegressor())  # Change to ExtraTreesRegressor

# Fit the model on the training data
model.fit(X_train, y_train)

# Predict on the test data
y_pred = model.predict(X_test)

# Calculate RMSE and R2_score
rmse = calculate_rmse(y_test, y_pred)
r2score = calculate_R2_score(y_test, y_pred)


# ------------------------------------------------
### OUTPUT ###
print("RMSE:", rmse)
print("R2_score:", r2score)

MultiOutputRegressor(estimator=ExtraTreesRegressor())

RMSE: 80086.11983090812
R2_score: 0.9120111142916353

In [ ]:
# fin